/// Models for self-hosted music servers (Feature Group: servers).
///
/// One configuration row per server; credentials never live in these
/// objects (they stay in the platform secure store behind
/// [MusicServerSecretStore]) so a exported registry JSON leaks nothing.
library;

import 'package:spotimusic/models/track.dart';

/// Supported self-hosted back-ends.
enum MusicServerKind {
  jellyfin('Jellyfin'),
  navidrome('Navidrome'),
  subsonic('Subsonic'),
  airsonic('Airsonic'),
  plex('Plex');

  const MusicServerKind(this.label);

  final String label;

  static MusicServerKind fromName(Object? name) {
    final text = name?.toString().trim().toLowerCase() ?? '';
    for (final kind in MusicServerKind.values) {
      if (kind.name == text) return kind;
    }
    return MusicServerKind.subsonic;
  }

  /// Whether this family speaks the Subsonic REST API (Navidrome and
  /// Airsonic share the Subsonic dialect with tiny differences).
  bool get isSubsonicFamily =>
      this == MusicServerKind.subsonic ||
      this == MusicServerKind.navidrome ||
      this == MusicServerKind.airsonic;
}

/// User-facing connection settings for one server.
class MusicServerConfig {
  const MusicServerConfig({
    required this.id,
    required this.kind,
    required this.baseUrl,
    this.displayName = '',
    this.username = '',
    this.preferDirectPlay = true,
    this.maxBitrateKbps = 0,
    this.transcodeFormat = '',
    this.enabled = true,
  });

  /// Stable unique id (uuid-ish string generated by the registry).
  final String id;

  final MusicServerKind kind;

  /// Base URL without trailing slash, e.g. `https://music.home:443`.
  final String baseUrl;

  /// Optional friendly name; defaults to host when empty.
  final String displayName;
  final String username;

  /// Prefer the original file (progressive, cacheable) over adaptive
  /// transcodes.
  final bool preferDirectPlay;

  /// Transcode ceiling in kbps (0 = unlimited/original).
  final int maxBitrateKbps;

  /// Preferred transcode container/codec (`flac`, `aac`, `mp3`, `opus`).
  final String transcodeFormat;

  final bool enabled;

  String get effectiveName =>
      displayName.trim().isEmpty ? _hostOf(baseUrl) : displayName.trim();

  String get sourceTag => '${kind.name}:$id';

  MusicServerConfig copyWith({
    String? baseUrl,
    String? displayName,
    String? username,
    bool? preferDirectPlay,
    int? maxBitrateKbps,
    String? transcodeFormat,
    bool? enabled,
  }) => MusicServerConfig(
    id: id,
    kind: kind,
    baseUrl: baseUrl ?? this.baseUrl,
    displayName: displayName ?? this.displayName,
    username: username ?? this.username,
    preferDirectPlay: preferDirectPlay ?? this.preferDirectPlay,
    maxBitrateKbps: maxBitrateKbps ?? this.maxBitrateKbps,
    transcodeFormat: transcodeFormat ?? this.transcodeFormat,
    enabled: enabled ?? this.enabled,
  );

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'kind': kind.name,
    'base_url': baseUrl,
    'display_name': displayName,
    'username': username,
    'prefer_direct_play': preferDirectPlay,
    'max_bitrate_kbps': maxBitrateKbps,
    'transcode_format': transcodeFormat,
    'enabled': enabled,
  };

  static MusicServerConfig? fromJson(Object? raw) {
    if (raw is! Map) return null;
    final id = raw['id']?.toString() ?? '';
    final baseUrl = raw['base_url']?.toString() ?? '';
    if (id.isEmpty || baseUrl.isEmpty) return null;
    return MusicServerConfig(
      id: id,
      kind: MusicServerKind.fromName(raw['kind']),
      baseUrl: baseUrl,
      displayName: raw['display_name']?.toString() ?? '',
      username: raw['username']?.toString() ?? '',
      preferDirectPlay: raw['prefer_direct_play'] == true,
      maxBitrateKbps: (raw['max_bitrate_kbps'] as num?)?.toInt() ?? 0,
      transcodeFormat: raw['transcode_format']?.toString() ?? '',
      enabled: raw['enabled'] != false,
    );
  }

  static String _hostOf(String url) {
    final uri = Uri.tryParse(url);
    return uri?.host ?? url;
  }
}

/// Secure storage port for server credentials. Production binds to the
/// app keystore (`SecureStore.writeToken`/`readToken`); tests bind fakes.
abstract class MusicServerSecretStore {
  Future<String?> password(String serverId);
  Future<void> setPassword(String serverId, String value);
  Future<String?> token(String serverId);
  Future<void> setToken(String serverId, String value);
  Future<void> clear(String serverId);
}

/// One search/track result from a server, convertible to the app [Track]
/// currency so queues, downloads and playback work unchanged.
class ServerTrack {
  const ServerTrack({
    required this.itemId,
    required this.title,
    required this.artist,
    required this.album,
    this.albumId = '',
    this.artistId = '',
    this.coverUrl = '',
    this.durationSeconds = 0,
    this.bitrateKbps = 0,
    this.codec = '',
    this.lossless = false,
    this.year,
  });

  /// Server-native item id (Jellyfin UUID, Subsonic numeric id, Plex
  /// ratingKey).
  final String itemId;
  final String title;
  final String artist;
  final String album;
  final String albumId;
  final String artistId;
  final String coverUrl;
  final int durationSeconds;
  final int bitrateKbps;
  final String codec;
  final bool lossless;
  final int? year;

  Track toTrack(MusicServerConfig config) => Track(
    id: itemId,
    name: title,
    artistName: artist,
    albumName: album,
    artistId: artistId,
    albumId: albumId,
    coverUrl: coverUrl,
    duration: durationSeconds,
    releaseDate: year == null ? null : '$year',
    source: config.sourceTag,
    audioQuality: lossless ? 'LOSSLESS' : 'HIGH',
  );
}

/// Connection failures surfaced to the settings UI.
class MusicServerException implements Exception {
  const MusicServerException(this.message, {this.kind = 'network'});

  final String message;

  /// `network` | `auth` | `parse` | `config`.
  final String kind;

  bool get isAuth => kind == 'auth';

  @override
  String toString() => 'MusicServerException($kind): $message';
}
