// GENERATED FILE - DO NOT EDIT
// Generated by: dart run tool/check_translations.dart 70
// Only languages with >= 70% translation completion are included.
// Translation is measured by key existence against the template ARB
// (app_en.arb): keys missing from a locale fall back to English at runtime
// through gen-l10n, so this measures what users actually see.
//
// To regenerate, run: dart run tool/check_translations.dart 70

import 'package:flutter/widgets.dart';

/// Minimum translation completion threshold used to filter languages.
const int translationThreshold = 70;

/// List of locales that meet the translation threshold.
/// Only these languages will be available in the app.
const List<Locale> filteredSupportedLocales = <Locale>[
  Locale('en'),
  Locale('de'),
  Locale('es', 'ES'),
  Locale('fr'),
  Locale('id'),
  Locale('ja'),
  Locale('ko'),
  Locale('pt', 'PT'),
  Locale('ru'),
  Locale('tr'),
  Locale('uk'),
];

/// Set of locale codes for quick lookup.
const Set<String> filteredLocaleCodes = <String>{
  'en',
  'de',
  'es_ES',
  'fr',
  'id',
  'ja',
  'ko',
  'pt_PT',
  'ru',
  'tr',
  'uk',
};
